[package]
name = "traditional-roguelike"
version = "0.1.0"
edition = "2021"

[dependencies]
hot-assets = { version = "0.1.0", path = "../hot-assets" }
macroquad = "0.4.13"
maplit = "1.0.2"
rand = "0.8.5"
